### ISSUE TITLE
Taking too long to result

### ISSUE THREAD

**Issue by rajkaran** [exposebox/node-thrift2-hbase#12]
Below is my query which I am running against database containing only 140, 000 rows.
```
scan.add('patient_visit');    //scan all family info
scan.setLimit(50000); //search how much number rows

scan.setFilterString(
	"SingleColumnValueFilter('patient_visit', 'assignedPointOfCare', =, 'binary:WH-ED')"
	+" OR SingleColumnValueFilter('patient_visit', 'triageDatetime', >=, 'binary:20171116000000')"
	+" AND SingleColumnValueFilter('patient_visit', 'triageDatetime', <=, 'binary:20171117000000')"
);

HBase.scan('idrive_dev_hbase', scan, function(err,data){ //get users table
	if(err){
		console.log('error:',err);
		return;
	}
	console.log('Total rows scanned:', data.length);
	console.timeEnd('dbsave')
});
```
Never get to see any result as query took longer than 10 mins and I ran out of patience.

HBase - 1.1.2
thrift.hbase - one comes with module. (0.98.4)

Am I doing something wrong?

**Comment by moshewe** [comment]
I'm scanning using the exact code in the repository without any problems, although I use start and end rows. Can you see the query being executed in the Thrift server on your HBase machines?

**Comment by rajkaran** [comment]
I can not use start and end rows as I will not know them at the time of querying.

I am running thrift2 server in foreground and I am not seeing anything about submission for this query or any other query.

I am not sure where to look for submission info.

**Comment by moshewe** [comment]
Can you try performing a sanity check with known keys to ensure a scan with start/end rows works?
Do any queries work using the library?

You should see a log for incoming requests on your Thrift2 server on one of your HBase machines when you perform any query using the library.

**Comment by rajkaran** [comment]
No Luck.. still taking long..
```
scan.add('patient_visit');    //scan all family info
scan.setLimit(50000); //search how much number rows
scan.setStartRow('427073106-WH274801-1509029106627');   //start rowKey
scan.setStopRow('436194590-WH337358-1511272120896');   //stop rowKey

scan.setFilterString(
	"SingleColumnValueFilter('patient_visit', 'assignedPointOfCare', =, 'binary:WH-ED')"
	+" OR SingleColumnValueFilter('patient_visit', 'triageDatetime', >=, 'binary:20171116000000')"
	+" AND SingleColumnValueFilter('patient_visit', 'triageDatetime', <=, 'binary:20171117000000')"
);

HBase.scan('idrive_dev_hbase', scan, function(err,data){ //get users table
	if(err){
		console.log('error:',err);
		return;
	}
	console.log('Total rows scanned:', data.length);
	console.timeEnd('dbsave')
});
```
It's not like it never runs it does run if I change setLimit value to 1000.

Where can I find this log. In secure shell where I have started Thrift2 server I do not see anything.
`hbase thrift2 start` Am I missing any configuration.

**Comment by moshewe** [comment]
Can you try get-ing a known rowkey to make sure the thrift2 communication between you client and server works?
If I understood you correctly, the query works correctly and in a timely manner with limit set to 1000?...

The thrift2 server is supposed to already be running on your HBase machines. I use HDP and my logs are under `/var/log`. You're not supposed to fire it up to see the logs.

**Comment by rajkaran** [comment]
These two queries works
```
scan.add('patient_visit');    //scan all family info
scan.setLimit(10000); //search how much number rows

scan.setFilterString(
	"SingleColumnValueFilter('patient_visit', 'assignedPointOfCare', =, 'binary:WH-ED')"
	+" OR SingleColumnValueFilter('patient_visit', 'triageDatetime', >=, 'binary:20171116000000')"
	+" AND SingleColumnValueFilter('patient_visit', 'triageDatetime', <=, 'binary:20171117000000')"
);

HBase.scan('idrive_dev_hbase', scan, function(err,data){ //get users table
	if(err){
		console.log('error:',err);
		return;
	}
	console.log('Total rows scanned:', data.length);
	console.timeEnd('dbsave')
});
```

Result:
Total rows scanned: 50000
Time took: 101536.949ms

```
scan.add('patient_visit');    //scan all family info
scan.setLimit(50000); //search how much number rows
scan.setFilterString(" RowFilter(=, 'substring:433373332')" );

HBase.scan('idrive_dev_hbase', scan, function(err,data){ //get users table
	if(err){
		console.log('error:',err);
		return;
	}
	console.log('Total rows scanned:', data.length);
	console.timeEnd('dbsave')
});
```

Result:
Total rows scanned: 7
Time took: 1360.922ms

But I can't limit results to 1000. We gets 25000 transactions a day and we may need to extract for varying time period from a day to years.

**Comment by rajkaran** [comment]
closed by mistake...

**Comment by moshewe** [comment]
This sounds like network/storage slowness.

Have you tried using `scanLoopFetch` instead? It's in the `client` file. The feature has been tested by another user (see his PR), but I haven't used it myself. It's not directly available right now, but you are more than welcome to submit a PR for it.

**Comment by rajkaran** [comment]
so far I have tried this
```
var HBase = require('node-thrift2-hbase');
var hbaseService = HBase(config);
var hbasePool = hbaseService.clientPool;

hbasePool.acquire(function (err, hbaseClient) {
	var scan = hbaseClient.scanLoopFetch()
});
```

which is throwing an error
```
TypeError: Cannot read property 'openScanner' of undefined
    at Client.scanLoopFetch (/var/www/html/query-hbase-rest-api/node_modules/node-thrift2-hbase/src/client.js:208:16)
    at /var/www/html/query-hbase-rest-api/server/boot/hbase-rpc.js:19:32
    at /var/www/html/query-hbase-rest-api/node_modules/generic-pool/lib/generic-pool.js:368:9
    at callbackWrapper (/var/www/html/query-hbase-rest-api/node_modules/node-thrift2-hbase/src/client.js:61:17)
    at .<anonymous> (/var/www/html/query-hbase-rest-api/node_modules/node-thrift2-hbase/src/client.js:99:17)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (/var/www/html/query-hbase-rest-api/node_modules/thrift/lib/nodejs/lib/thrift/connection.js:89:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by moshewe** [comment]
This code has not been standardized in our library - but we have at least one happy user using it. I haven't used it myself. You can look into the source code yourself, it's a small codebase.

PRs welcome!

**Comment by eranbetzalel** [comment]
Scan streaming (openScanner) is now available.

https://github.com/exposebox/node-thrift2-hbase/commit/ed5699dbbd93a2f72637b74560b055ada7f997d4

**Comment by rajkaran** [comment]
It is such an old query I shall close it now.

Is this library supports HBase 2.1.6?
