### ISSUE TITLE
Thrift close connection error

### ISSUE THREAD

**Issue by kangjianfeng** [exposebox/node-thrift2-hbase#14]
hello,i use it,throw the error,then the program stoppted,how do it?thank you .

**Comment by moshewe** [comment]
Can you please be more specific?
Can you show us the code that throws this error? Can you show us the error?

**Comment by kangjianfeng** [comment]
this is some code：
```
var hbaseconfig = {
	hosts:['192.168.1.11'],
	port:"9090"
};
var client = require('node-thrift2-hbase')(hbaseconfig);
var log=require('./log.js');
var util= require('util');


function SaveDataToHBase(obj,tableType){
	var RowKey=obj.imei+obj.datetime;	
	var put = client.Put(RowKey);
	for(var key in obj){
		put.add('basic_cf',key,obj[key]);
	}
	client.put(tableType.toLowerCase(),put,function(err){
		if(err){
			log.Save(util.format('save hbase err!:%s',err),'error');
		}else{
			console.log('save ok'+RowKey);
		}
	});	
}
```

When the program starts to run correctly, this error will appear in one days and two days, and then the program will not work. How can I catch the error? Thanks 

the err is "Thrift close connection error 192.168.1.11"

**Comment by kangjianfeng** [comment]
i see the code in "src>client.js"

```
            client.connection.on('close', function () {
                console.log('Thrift close connection error', client.host);
                callbackWrapper(new Error('Thrift close connection'), client);
            });

            client.connection.on('timeout', function () {
                console.log('Thrift timeout connection error', client.host);
                callbackWrapper(new Error('Thrift timeout connection'), client);
            });
```

**Comment by moshewe** [comment]
Please make sure you are running the Thrift2 server for HBase on the target
host. You get the error once you try to connect to the Thrift server.

**Comment by kangjianfeng** [comment]
because the err is throwed by client.js,how  catch  the error in my code? thanks!

**Comment by moshewe** [comment]
You can wrap `SaveDataToHBase` in a try/catch block. I would generally
advise against this unless you are working in a low-connectivity
environment.

**Comment by kangjianfeng** [comment]
yes,I don't want to use this way, but is there any other way to catch it? Thanks

**Comment by moshewe** [comment]
The library does not provide any way to catch this error built-in.
Being able to connect to the Thrift2 server on your HBase machine is a
precondition for this library to work.

**Comment by kangjianfeng** [comment]
I write try/catch block in "SaveDataToHBase" ,but nothing catch? i stop hbase thrift2 service , no err can catch?

**Comment by Ran-P** [comment]
This solved

**Comment by Ran-P** [comment]
Bug solved
