### ISSUE TITLE
hbase thrift2 Memory has been growing

### ISSUE THREAD

**Issue by kuake** [exposebox/node-thrift2-hbase#9]
```
var put = function(region, obj, callback){
  var key = obj.key;

  var put = new Hbase.Put(key);
  put.add('p', 'a', obj.a.toString());
  put.add('p', 'b', obj.b.toString());

  Hbase.put(tbName, put, function(err, success){
    if(err){
      logger.error('put miui_metok:probe_location:',err);
    }
    callback(err, success);
  });
};
```
above as my code, but i find hbase thrift2 memory has been growing, and frequently triggered minor GC and full GC.
Scan method is OK.
Do you have any good advice? 
Thanks for your help!

**Comment by moshewe** [comment]
When you say it's triggering GCs, you mean on the HBase server or on your NodeJS server? (I assume it's the HBase server).
`tbName` is not defined here, but I don't think that's the problem - it should just fail.

What version of HBase are you running?
What version is the Thrift compiler you have used to compile the interface?

**Comment by kuake** [comment]
server: ```hbase-daemon.sh start thrift2 -p 8000```
tbName is local variable: ```var tbName = 'myTableName';```

Hbase 0.98.11
thrift@0.9.3

you mean I must use Hbase 0.98.11 Hbase.thrift to compile?

**Comment by moshewe** [comment]
Now I remember!
We had the same issue and traced is back to a known memory leak in the HBase Thrift server implementation. According to the JIRA, # **Not all users get this bug.**

We've solved this by having a simple script restart the daemon once every day (preferably when there's the least amount of traffic, e.g. the middle of the night).

On HBase 1.1.2 we don't see this phenomenon.

**Comment by kuake** [comment]
Thank u very much!

Do  you have the JIRA URL? or, where to find more info?

**Comment by moshewe** [comment]
https://issues.apache.org/jira/browse/HBASE-2674
https://issues.apache.org/jira/browse/HBASE-4633

I think this is worth noting (again): **HBase 1.1.2 does NOT have this problem.**

**Comment by moshewe** [comment]
@kuake 
Can we close this issue? Did restarting the thrift service work for you as it did for us?

**Comment by kuake** [comment]
ok, Thanks!
Like you, I restarting the thrift service every day.
Is there a way to update thrift service to 1.1.2 only?

**Comment by moshewe** [comment]
Thrift is a real-time* communications protocol. HBase is accessible via a Thrift interface - that is, HBase provides an implementation of certain methods over the Thrift protocol (the HBase Thrift service) for query access. HBase provides a Thrift definition file which you can compile to whatever programming language you wish in order to communicate with the HBase Thrift service. The Thrift service comes together with your HBase, so you can't update it separately from HBase- you have to upgrade your HBase for that.

**Comment by kuake** [comment]
I really appreciate your detailed answer!
